const PARAGRAPH1 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et ipsum suscipit, dignissim purus ac, tristique magna. Nam sit amet tincidunt massa, ut tempus diam. Mauris aliquet magna eu lorem varius, ut tincidunt augue aliquam. Sed fringilla tortor vitae hendrerit semper. Pellentesque eget pulvinar magna, quis tempus urna. Quisque felis augue, elementum eget mollis nec, feugiat et quam. Curabitur finibus tristique velit, eu facilisis diam pulvinar vitae. Proin ac sodales eros, sit amet venenatis elit. Maecenas egestas ipsum in velit ullamcorper rhoncus. Cras suscipit, ligula et rhoncus sodales, libero sapien feugiat lectus, at suscipit erat justo eget sapien. Maecenas imperdiet nisl in pellentesque mattis. Proin justo massa, tincidunt sed turpis nec, varius mattis urna. Cras tincidunt hendrerit sem, id consequat ante ultricies at. Mauris at lectus laoreet, dapibus nibh vitae, mollis lorem. Praesent interdum at dolor at accumsan. Fusce et ipsum in urna ultricies accumsan.'

const PARAGRAPH2 = 'In hac habitasse platea dictumst. Ut ut interdum magna. Donec suscipit augue at neque gravida, quis molestie justo tempor. Mauris non leo dolor. Phasellus purus lectus, dapibus non aliquet quis, viverra tincidunt elit. Maecenas accumsan nisi id tincidunt finibus. Maecenas eu nisi cursus, sodales tellus vitae, mattis dui. Duis pharetra odio sit amet neque lobortis vestibulum. Aliquam dignissim in metus vel euismod. Etiam nec elit non risus accumsan placerat at eu nisi. Cras consectetur porttitor metus, id lobortis libero consequat sit amet. Suspendisse nec ultrices tellus. In hac habitasse platea dictumst. Aenean mollis egestas quam sed ornare.'

const PARAGRAPH3 = 'Sed pharetra eleifend elit eget hendrerit. Pellentesque et porttitor est, in ornare mi. Vestibulum molestie eu lorem vel egestas. Nullam in faucibus nibh. Nunc efficitur nisl at faucibus dignissim. Donec laoreet tortor id justo iaculis, id laoreet purus vehicula. Maecenas vel purus elit. Maecenas aliquet arcu tincidunt fringilla malesuada. Pellentesque varius placerat lectus, vel ornare arcu posuere eget. Morbi auctor scelerisque magna, sed fringilla sem finibus sed. Aliquam elementum sapien sed massa elementum, eget porttitor mi feugiat. Aliquam mattis libero placerat orci lacinia hendrerit.'

const PARAGRAPH4 = 'In sapien tortor, tempus a risus id, gravida dignissim leo. Donec efficitur, odio vitae vestibulum iaculis, purus risus tincidunt eros, eu elementum felis odio quis ipsum. In porta orci id dignissim volutpat. Sed eu ornare urna. Nam a gravida eros. Nullam nec magna lobortis, consectetur quam ut, consectetur ex. Aliquam id dui sed nulla sagittis pretium. Sed ac augue ut tortor placerat luctus a eu tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porta nisi vitae odio consectetur, id varius urna iaculis. Phasellus ac eros justo.'

const PARAGRAPH5 = 'Aenean cursus, purus eu auctor rhoncus, lacus erat consequat enim, eu feugiat elit ipsum eu tellus. Sed enim mi, pellentesque quis ante id, pretium auctor justo. Proin varius, sem nec consequat blandit, ex metus consectetur libero, ut molestie est orci in erat. Vivamus lacinia dui et nulla aliquet sodales. Etiam et orci enim. Ut et dignissim odio. Morbi faucibus luctus purus. Cras dolor neque, lobortis vel efficitur et, mollis eget velit. Donec ultrices auctor diam in tincidunt. Nam efficitur, erat ut eleifend porta, eros augue sollicitudin risus, viverra vulputate nibh augue eu magna. In bibendum dui eget eleifend ornare. Suspendisse convallis eros lorem. Vestibulum lobortis semper condimentum. Nunc vitae tempor nibh, at convallis nibh. Nam eget sollicitudin purus.'

export {
  PARAGRAPH1,
  PARAGRAPH2,
  PARAGRAPH3,
  PARAGRAPH4,
  PARAGRAPH5
}